

jammy-jre:
	docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v .:/mnt --privileged  ubuntu:22.04  sh /mnt/ubuntu.sh-jre
jammy-jdk:
	docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v .:/mnt --privileged  ubuntu:22.04  sh /mnt/ubuntu.sh-jdk
