FROM ubuntu:24.04
ARG GRADLE_VER 8.6

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update \
    && apt-get install -y openjdk-21-jre curl \
    && apt-get clean &&  rm -rf /var/cache/apt /var/lib/apt /root/.cache /root/.gradle



